<?php require_once( __DIR__ . '/parts/header.phtml' ); ?>

<?php require_once( __DIR__ . '/parts/top-navigation.phtml' ); ?>

<div class="container-fluid">
  <div class="row">
    <?php require_once( __DIR__ . '/parts/sidemenu.phtml' ); ?>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4" style="margin-top: 40px">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Inicio</h1>
          </div>

          <div class="card">
            <div class="card-header">
              Informação
            </div>
            <div class="card-body">
              <p class="card-text">Você está utilizando a versão <b>DESENV</b>, alguns módulos só estão disponiveis nesta versão por questões de segurança. <br>
              Se você não estiver em ambiente de desenvolvimento, é recomendado que altere a versão.</p>
              <a href="#" class="btn btn-primary">Alterar para versão de Produção</a>
            </div>
          </div>
    </main>
    
  </div>  
</div>

<?php require_once( __DIR__ . '/parts/footer.phtml' ); ?>
<script>
  $(document).ready(Admin.index.init);  
</script>