<form action="">
  <div class="form-group">
    <label for="name"><b>Nome</b></label>
    <input type="text" class="form-control" placeholder="Nome do seu modelo, middleware, controller">
  </div>

  <div class="form-group">
      <label><b>Criar um</b></label>
      <div class="custom-control custom-radio">
        <input type="radio" id="customRadio1" name="customRadio" class="custom-control-input">
        <label class="custom-control-label" for="customRadio1">Controller</label>
      </div>
      <div class="custom-control custom-radio">
        <input type="radio" id="customRadio2" name="customRadio" class="custom-control-input">
        <label class="custom-control-label" for="customRadio2">Middleware</label>
      </div>
      <div class="custom-control custom-radio">
        <input type="radio" id="customRadio2" name="customRadio" class="custom-control-input">
        <label class="custom-control-label" for="customRadio2">Model</label>
      </div>
      <div class="custom-control custom-radio">
        <input type="radio" id="customRadio2" name="customRadio" class="custom-control-input">
        <label class="custom-control-label" for="customRadio2">Controller e Model</label>
      </div>
    </div>

    <div class="form-group">
      <label for=""><b>Opções adicionais</b></label>
      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="customCheck1">
        <label class="custom-control-label" for="customCheck1"> Implementar rotas get / list / delete / create / update </label>
      </div>
    </div>

    <button class="btn btn-primary" type="submit">Criar</button>
  </div>
</form>