<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title> Painel Administrativo </title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" media="screen" href="/assets/AdminModule/css/bootstrap.min.css" />
  <link rel="stylesheet" type="text/css" media="screen" href="/assets/AdminModule/css/admin<?= _DEV_ ? '' : '.min' ?>.css" />
</head>
<body>