<nav class="col-md-2 d-none d-md-block bg-light sidebar" style="margin-top: 40px;">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link " href="#">
          <span data-feather="home"></span>
          <a href="/admin">Inicio <span class="sr-only">(current)</span></a>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="#">
        <a href="/admin">Geral</a>
        </a>
      </li>

      <?php if( _ADMIN_DEV_ ): ?>
        <li class="nav-item">
          <a class="nav-link " href="#">
          <a href="/admin">Banco de Dados</a>
          </a>
        </li>
      <?php endif; ?>

      <li class="nav-item">
        <a class="nav-link " href="#">
        <a href="/admin">Segurança</a>
        </a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link " href="#">
        <a href="/admin">Integrações</a>
        </a>
      </li>
    </ul>


  <?php if( _ADMIN_DEV_ ): ?>
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Modelos</span>
      <a class="d-flex align-items-center text-muted" href="#">
        <span data-feather="plus-circle"></span>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">
      <?php if( is_array( $models ) ): ?>
        <?php foreach( $models as $model ): ?>
          <li class="nav-item">
            <a class="nav-link" href="admin/manage/<?= mb_strtolower($model); ?>">
              <span data-feather="file-text"></span>
              <?= $model ?>
            </a>
          </li>
        <?php endforeach; ?>
      <?php endif; ?>
    </ul>
  <?php endif; ?>
  </div>
</nav>