<table class="table" id="list-data">
  <thead>
    <tr>
    <?php foreach( $modelArray as $key => $value ): ?>
      <th scope="col"><?= ucfirst( $key ) ?></th>
    <?php endforeach; ?> 
    <th>Ação</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach( $table as $rowID => $row ): ?>
    <tr id="<?= $rowID ?>">
      <?php foreach( $modelArray as $key => $value ): ?>
      <td id="<?= $rowID ?>-<?= $key ?>" ondblclick="Admin.manage.editField('<?= $key ?>', '<?= $row[$key] ?>', '<?= $rowID ?>-<?= $key ?>')">
        <?= $G::__($row[$key]) ?>
      </td>
      <?php endforeach; ?> 
      <td> 
        <button type="button" class="btn btn-danger" onclick="Admin.manage.delete(<?= $rowID ?>, '<?= $modelName ?>')">Deletar</button>
        <button type="button" class="btn btn-primary" onclick="Admin.manage.commit(<?= $rowID ?>, '<?= $modelName ?>')" disabled id="save">Salvar</button> 
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>